### ISSUE TITLE
deploy-node-app requires kubectl > 1.14.1

### ISSUE THREAD

**Issue by fineline** [kubesail/deploy-to-kube#12]
I am trying out KubeSail with a sample NodeJS app. Running deploy-node-app, it gets as far as the command:

```
kubectl --context=kubesail-fineline apply -f deployment-prod.yaml
```

And gives the following error:

```
error: SchemaError(io.k8s.api.authorization.v1.SubjectAccessReviewSpec): invalid object doesn't have additional properties
```

If I try and run that command directly at the command line I get the same error. 

I tested another kubectl command:

```
kubectl get deployments
```

And that one runs OK and successfully retrieves the list of my kubesail deployments.

**Comment by fineline** [comment]
I found the issue. The current install of Docker Desktop for MacOS includes kubernetes-cli v 1.10. I installed the latest stable version 1.14 via homebrew and the problem was resolved.

**Comment by pastudan** [comment]
@fineline thanks for the report! I just pushed up a fix (https://github.com/kubesail/deploy-node-app/commit/8fe6d246d503b1112aaa17405adf52b0de5fdaa8) that should provide a more helpful message for future users, and I will publish a version with this fix to NPM soon. Cheers!

**Comment by pastudan** [comment]
Re-opening this since a better solution is to include the kubectl binary locally with the node module itself.

**Comment by erulabs** [comment]
Closing this as deploy-node-app 2.0 will not require kubectl at all (although it will still of course be a suggested download in documentation!)
