### ISSUE TITLE
npx: installed 72 in 15.371s Unexpected token {

### ISSUE THREAD

**Issue by mritunjay10** [kubesail/deploy-to-kube#17]
Whenever I run  - 

`npx deploy-node-app`

It throws the following error -

**npx: installed 72 in 15.371s Unexpected token {**

**Comment by pastudan** [comment]
@Mritunjay10 can you share what node version you are on? `node -v`

**Comment by pastudan** [comment]
I suspect you are on an older version, and we likely don't do a good job checking for that yet. Should be easy to add if that's the case

**Comment by mritunjay10** [comment]
Updating the node along with npm fixed the issue.

Thanks!!

**Comment by erulabs** [comment]
🥂 Marking as resolved
