### ISSUE TITLE
"--squash" is only supported on a Docker daemon with experimental features enabled

### ISSUE THREAD

**Issue by david-gorski** [kubesail/deploy-to-kube#26]
Trying to run `npx deploy-node-app` results in this error when no documentation mentions the need for enabling experimental features. 

Perhaps remove -squash or include something about this in the setup?

**Comment by erulabs** [comment]
Ack! Good find - I suppose @pastudan and I (the main authors of this library) probably both have experimental features enabled on all our workstations. Will remove this option for now!

**Comment by erulabs** [comment]
This has been merged and released in 1.5.1! Thanks!
