### ISSUE TITLE
Error in configuration: context was not found for specified context: undefined

### ISSUE THREAD

**Issue by david-gorski** [kubesail/deploy-to-kube#28]
Trying to run deploy-node-app locally results in an error while trying to run `kubectl --context="undefined"...`

**Comment by erulabs** [comment]
Ack - that's a strange one. Do you have a `~/.kube` directory? What about a working kubectl context in general? Any info you can provide about the state of your kubectl setup locally would be helpful. Looking into this...

**Comment by erulabs** [comment]
The output of the command would also be helpful - if you saw `Using Kubernetes context`... or not indicates two different code paths

**Comment by erulabs** [comment]
@Fugos let me know if you get a chance to provide a bit more info - you can also try the patch above (#29) - it won't solve the issue but hopefully the debug log provides a hint. Thanks for using the tool!

**Comment by david-gorski** [comment]
The issue was solved by just running `deploy-node-app local` which prompted an update to inf/prod/deployment.yaml which seems to have fixed the issue. Initially I had run the command with `-f compose`.

I had a ~/.kube/config file provided from the kubesail dashboard. 

I did not see "Using Kubernetes context" in the output. The complete output was this:
```
npx deploy-node-app local -f compose
npx: installed 104 in 5.7s
!! Preparing to deploy to local...
!! Using project name authority...
? What sort of application is this? Server (An app that listens for network requests)
? What port does your application listen on? (If not applicable, press enter to continue
) 5000
? Which protocol does your application speak? http
? What is your docker hub username? dgorski66

!! The image dgorski66/authority:107175c is already in use - setting tag to 107175c-1570119694


!! You are using Docker Hub. If the repository "dgorski66/authority" does not exist, it may be automatically created with PUBLIC access!
!! You can visit https://cloud.docker.com/repository/create to create a private repository instead.
!! In any case, make sure you have all secrets in your ".dockerignore" file.

? Is this a public or private repository? Private (recommended)
? What is your docker hub password? [hidden]
Error in configuration: context was not found for specified context: undefined
>> Command "kubectl --context="undefined"           create secret docker-registry "****"           --docker-server="https://index.docker.io/v1/"           --docker-username="dgorski66"           --docker-password="****"" failed to run
```

**Comment by erulabs** [comment]
Ack, we for sure shouldn't try to create kube image pull secrets in compose mode - will fix this shortly!

**Comment by erulabs** [comment]
I apologize for the slow response to this - PR #31 should do the trick. Will test and release a new version shortly. Thanks again for the report!
