### ISSUE TITLE
Custom Dockerfile/skaffold.yml support

### ISSUE THREAD

**Issue by ishumilova** [kubesail/deploy-to-kube#45]
From the developer's perspective (and from kubesail customer's perspective), I would definitely be happy if you add support of building from my custom Dockerfile & skaffold.yml files; otherwise, the CI/CD integration between kubesail and git is pointless since it can not build my scala projects.

**Comment by erulabs** [comment]
I hope it's OK if I re-open this issue - this is certainly a bug if deploy-node-app ignores Dockerfiles. I apologize for the slow response time here!

Should have a chance to resolve this tonight or tomorrow - will let you know! Thanks for the report!!

**Comment by erulabs** [comment]
As an edit: I do not believe the problem is here in DNA (DNA honors the existing Dockerfile), but rather with KubeSail.com's CI system and how it _uses_ DNA. We'll get this sorted!

**Comment by erulabs** [comment]
We now always respect existing Dockerfiles - this carries over to KubeSail as well. Skaffold support is going to be a bigger project, but we're looking forward to it! We'll try to keep you posted of the progress as much as possible :)
