### ISSUE TITLE
What software was used to generate the animated SVG in the readme.md?

### ISSUE THREAD

**Issue by vaaski** [kubesail/deploy-to-kube#5]
It looks pretty good and the fact that it's a vector graphic **and** animated satisfies me deeply.
I doubt that somebody wrote this by hand, although I couldn't find any kind of watermark comment in the SVG itself. So what was used?

Thanks.

**Comment by pastudan** [comment]
Thanks for noticing the little details! The thought of doing it by hand kills me 😆 

I ultimately used https://github.com/marionebl/svg-term-cli which was somewhat involved. I recorded the screen with asciinema and then fed it into to svg-term-cli with a custom profile and window.

I also tried the python based https://github.com/nbedos/termtosvg but was not as satisfied with the result. The animation would flash and filesize was 5x larger, but the process was far simpler.

**Comment by vaaski** [comment]
Thank you very much for the fast reply, I'll 110% use this to make my next readme look as good as yours ;)
