### ISSUE TITLE
Config file tool - cannot connect to localhost. 

### ISSUE THREAD

**Issue by theonlydaleking** [kubesail/deploy-to-kube#7]
`npx deploy-node-app` 

will then ask you if you would like to use the tool to create a Kubernetes config. if you hit yes, it opens a browser that goes to kubesail.com momentarily, then attempts to redirect back to localhost 

![Screen Shot 2019-04-24 at 4 37 44 pm](https://user-images.githubusercontent.com/15007856/56637570-4ede1d00-66af-11e9-94a7-237b6d6ec767.png)

**Comment by pastudan** [comment]
@theonlydaleking Thanks for the report!

Are you getting any error output on your terminal? My best guess is that you have a firewall or security rule that is preventing the callback webserver from starting locally.

For context, the KubeSail config is retrieved via https://github.com/kubesail/get-kubesail-config - The way this package works is by launching a webserver on a random port on localhost. We open a browser and direct you to kubesail.com which redirects to you back to localhost with your config data. If the callback webserver can't start for some reason, then you'd see this error in your browser. You should however also be seeing some console output that explains why it can't start. If not, could you try running `npx get-kubesail-config` directly? Thanks!

**Comment by theonlydaleking** [comment]
@pastudan thanks for the reply, sorry we had a public holiday here yesterday. 

The terminal gives me this: 

```
fs.js:120
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/admin/.kube/config'
    at Object.openSync (fs.js:449:3)
    at Object.writeFileSync (fs.js:1211:35)
    at Server.<anonymous> (/Users/admin/.npm/_npx/45004/lib/node_modules/deploy-node-app/node_modules/get-kubesail-config/index.js:174:12)
    at Server.emit (events.js:197:13)
    at parserOnIncoming (_http_server.js:677:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
```

not sure if this is an issue with running it on mac?

**Comment by pastudan** [comment]
Thanks so much for the fix! I am embarassed https://github.com/kubesail/get-kubesail-config/issues/1 was open so long. I must have forgot!
