### ISSUE TITLE
calls to "execSync" should inherit users environment

### ISSUE THREAD

**Issue by erulabs** [kubesail/deploy-to-kube#9]
A reminder for myself, will issue a PR shortly.

Calls to execSync should almost always inherit the users environment variables, particularly when using `docker` or `kubectl` cli tools. This will allow users to override DOCKER_HOST, KUBECONFIG, etc, and in general behave more often "as expected" (ie: docker-machine would currently not work properly, as it relies on environment variables being passed to `docker`).

A wrapper like:

```javascript
const execSyncWithEnv = (cmd, args, options = {}) => {
  execSync(cmd, args, Object.assign({}, options, {
    env: Object.assign({}, process.env, options.env)
  }));
}
```

Should be all we need

**Comment by pastudan** [comment]
this is done now

**Comment by pastudan** [comment]
test
